# Generated by Django 4.2.30 on 2026-05-12 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xóa')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề bài đăng')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('account_code', models.CharField(max_length=50, unique=True, verbose_name='Mã số tài khoản')),
                ('thumbnail', models.TextField(blank=True, null=True, verbose_name='Ảnh đại diện')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Giá bán')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Giá gốc')),
                ('discount_percent', models.IntegerField(default=0, verbose_name='Phần trăm giảm giá')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Đang bán'), ('RESERVED', 'Đang giữ chỗ'), ('SOLD', 'Đã bán'), ('LOCKED', 'Đang khóa'), ('HIDDEN', 'Tạm ẩn')], default='AVAILABLE', max_length=20, verbose_name='Trạng thái')),
                ('login_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Loại đăng nhập')),
                ('account_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Loại tài khoản')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Mô tả ngắn')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả chi tiết')),
                ('account_data', models.JSONField(default=dict, verbose_name='Dữ liệu game (JSON)')),
                ('sold_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian bán')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('is_hot', models.BooleanField(default=False, verbose_name='Hot')),
                ('views', models.IntegerField(default=0, verbose_name='Lượt xem')),
            ],
            options={
                'verbose_name': 'Tài khoản game',
                'verbose_name_plural': 'Danh sách tài khoản',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField(verbose_name='Đường dẫn ảnh')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='account.account', verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Ảnh tài khoản',
                'verbose_name_plural': 'Bộ sưu tập ảnh',
                'ordering': ['sort_order'],
            },
        ),
    ]
