# Generated by Django 4.2.30 on 2026-05-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Số tiền nạp')),
                ('method', models.CharField(max_length=50, verbose_name='Phương thức nạp')),
                ('transaction_image', models.TextField(blank=True, null=True, verbose_name='Ảnh minh chứng (Bill)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú người dùng')),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='Ghi chú Admin')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Đã từ chối')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian duyệt')),
            ],
            options={
                'verbose_name': 'Yêu cầu nạp tiền',
                'verbose_name_plural': 'Danh sách nạp tiền',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('transaction_code', models.CharField(max_length=50, unique=True, verbose_name='Mã giao dịch')),
                ('type', models.CharField(choices=[('DEPOSIT', 'Nạp tiền'), ('PURCHASE', 'Mua tài khoản'), ('REFUND', 'Hoàn tiền'), ('WITHDRAW', 'Rút tiền')], max_length=50, verbose_name='Loại giao dịch')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Số tiền')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Số dư trước')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Số dư sau')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phương thức')),
                ('status', models.CharField(choices=[('PENDING', 'Đang xử lý'), ('SUCCESS', 'Thành công'), ('FAILED', 'Thất bại'), ('CANCELLED', 'Đã hủy')], default='SUCCESS', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu bổ sung')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Giao dịch',
                'verbose_name_plural': 'Lịch sử giao dịch',
                'ordering': ['-created_at'],
            },
        ),
    ]
