# Generated by Django 4.2.30 on 2026-06-04 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã thẻ (Code)')),
                ('serial', models.CharField(max_length=50, unique=True, verbose_name='Số Serial')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Mệnh giá')),
                ('status', models.CharField(choices=[('ACTIVE', 'Hoạt động'), ('USED', 'Đã dùng'), ('LOCKED', 'Đã khóa')], default='ACTIVE', max_length=20, verbose_name='Trạng thái')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian sử dụng')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cards', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_cards', to=settings.AUTH_USER_MODEL, verbose_name='Người sử dụng')),
            ],
            options={
                'verbose_name': 'Thẻ nạp',
                'verbose_name_plural': 'Danh sách thẻ nạp',
                'ordering': ['-created_at'],
            },
        ),
    ]
