Table django_migrations {
  id integer [pk]
  app varchar(255)
  name varchar(255)
  applied datetime
}

Table django_content_type {
  id integer [pk]
  app_label varchar(100)
  model varchar(100)
}

Table auth_group_permissions {
  id integer [pk]
  group_id integer
  permission_id integer
}

Table auth_permission {
  id integer [pk]
  content_type_id integer
  codename varchar(100)
  name varchar(255)
}

Table auth_group {
  id integer [pk]
  name varchar(150)
}

Table user_user {
  id integer [pk]
  password varchar(128)
  last_login datetime
  is_superuser bool
  username varchar(150)
  first_name varchar(150)
  last_name varchar(150)
  is_staff bool
  is_active bool
  date_joined datetime
  created_at datetime
  updated_at datetime
  deleted_at datetime
  email varchar(254)
  avatar text
  phone varchar(20)
  balance decimal
  role varchar(30)
  status varchar(20)
  email_verified bool
}

Table user_user_groups {
  id integer [pk]
  user_id bigint
  group_id integer
}

Table user_user_user_permissions {
  id integer [pk]
  user_id bigint
  permission_id integer
}

Table game_game {
  id integer [pk]
  created_at datetime
  updated_at datetime
  deleted_at datetime
  name varchar(100)
  slug varchar(100)
  icon varchar(500)
  banner varchar(500)
  thumbnail varchar(500)
  description text
  theme_color varchar(20)
  sort_order integer
  is_hot bool
  status varchar(20)
}

Table account_accountimage {
  id integer [pk]
  image_url text
  sort_order integer
  created_at datetime
  account_id bigint
}

Table account_account {
  id integer [pk]
  created_at datetime
  updated_at datetime
  deleted_at datetime
  title varchar(255)
  slug varchar(255)
  account_code varchar(50)
  thumbnail text
  price decimal
  original_price decimal
  discount_percent integer
  status varchar(20)
  login_type varchar(50)
  account_type varchar(50)
  short_description text
  description text
  account_data text
  sold_at datetime
  is_featured bool
  is_hot bool
  views integer
  created_by_id bigint
  game_id bigint
}

Table django_admin_log {
  id integer [pk]
  object_id text
  object_repr varchar(200)
  action_flag smallint_unsigned
  change_message text
  content_type_id integer
  user_id bigint
  action_time datetime
}

Table notification_notification {
  id integer [pk]
  created_at datetime
  updated_at datetime
  title varchar(255)
  content text
  type varchar(50)
  is_read bool
  user_id bigint
}

Table order_orderitem {
  id integer [pk]
  price decimal
  delivery_data text
  created_at datetime
  account_id bigint
  order_id bigint
}

Table order_order {
  id integer [pk]
  created_at datetime
  updated_at datetime
  order_code varchar(50)
  total_price decimal
  payment_status varchar(20)
  delivery_status varchar(20)
  note text
  user_id bigint
}

Table payment_transaction {
  id integer [pk]
  created_at datetime
  updated_at datetime
  transaction_code varchar(50)
  type varchar(50)
  amount decimal
  balance_before decimal
  balance_after decimal
  payment_method varchar(50)
  status varchar(20)
  metadata text
  note text
  user_id bigint
}

Table payment_deposit {
  id integer [pk]
  created_at datetime
  updated_at datetime
  amount decimal
  method varchar(50)
  transaction_image text
  note text
  admin_note text
  status varchar(20)
  approved_at datetime
  approved_by_id bigint
  user_id bigint
}

Table django_session {
  session_key varchar(40) [pk]
  session_data text
  expire_date datetime
}


// Khai báo mối quan hệ (Foreign Keys)
Ref: auth_group_permissions.permission_id > auth_permission.id
Ref: auth_group_permissions.group_id > auth_group.id
Ref: auth_permission.content_type_id > django_content_type.id
Ref: user_user_groups.group_id > auth_group.id
Ref: user_user_groups.user_id > user_user.id
Ref: user_user_user_permissions.permission_id > auth_permission.id
Ref: user_user_user_permissions.user_id > user_user.id
Ref: account_accountimage.account_id > account_account.id
Ref: account_account.game_id > game_game.id
Ref: account_account.created_by_id > user_user.id
Ref: django_admin_log.user_id > user_user.id
Ref: django_admin_log.content_type_id > django_content_type.id
Ref: notification_notification.user_id > user_user.id
Ref: order_orderitem.order_id > order_order.id
Ref: order_orderitem.account_id > account_account.id
Ref: order_order.user_id > user_user.id
Ref: payment_transaction.user_id > user_user.id
Ref: payment_deposit.user_id > user_user.id
Ref: payment_deposit.approved_by_id > user_user.id
