# Generated by Django 4.2.30 on 2026-05-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xóa')),
                ('name', models.CharField(max_length=100, verbose_name='Tên game')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug (đường dẫn)')),
                ('icon', models.TextField(blank=True, null=True, verbose_name='Icon URL')),
                ('banner', models.TextField(blank=True, null=True, verbose_name='Banner URL')),
                ('thumbnail', models.TextField(blank=True, null=True, verbose_name='Thumbnail URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('theme_color', models.CharField(default='#008BFF', max_length=20, verbose_name='Màu chủ đạo')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Thứ tự sắp xếp')),
                ('is_hot', models.BooleanField(default=False, verbose_name='Game nổi bật')),
                ('status', models.CharField(choices=[('ACTIVE', 'Đang hoạt động'), ('HIDDEN', 'Tạm ẩn'), ('MAINTENANCE', 'Bảo trì')], default='ACTIVE', max_length=20, verbose_name='Trạng thái')),
            ],
            options={
                'verbose_name': 'Trò chơi',
                'verbose_name_plural': 'Danh sách trò chơi',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
