# Generated by Django 4.2.30 on 2026-05-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='banner',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Banner URL'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='game',
            name='icon',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Icon URL'),
        ),
        migrations.AlterField(
            model_name='game',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Thứ tự sắp xếp'),
        ),
        migrations.AlterField(
            model_name='game',
            name='thumbnail',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Thumbnail URL'),
        ),
    ]
