# Generated by Django 4.2.30 on 2026-05-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_banner_alter_game_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='attributes_schema',
            field=models.JSONField(blank=True, default=list, verbose_name='Cấu hình thuộc tính động'),
        ),
    ]
