# Generated by Django 4.2.30 on 2026-05-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('type', models.CharField(choices=[('SYSTEM', 'Hệ thống'), ('PAYMENT', 'Thanh toán'), ('ORDER', 'Đơn hàng'), ('PROMOTION', 'Khuyến mãi')], default='SYSTEM', max_length=50, verbose_name='Loại thông báo')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Danh sách thông báo',
                'ordering': ['-created_at'],
            },
        ),
    ]
