# Generated by Django 4.2.30 on 2026-06-08 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('title', models.CharField(max_length=255, verbose_name='Tên chuyên mục')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL thân thiện')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả chuyên mục')),
            ],
            options={
                'verbose_name': 'Chuyên mục',
                'verbose_name_plural': 'Danh mục bài viết',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề tin tức')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL thân thiện')),
                ('thumbnail', models.TextField(blank=True, null=True, verbose_name='Ảnh đại diện')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Mô tả ngắn')),
                ('content', models.TextField(verbose_name='Nội dung chi tiết')),
                ('status', models.CharField(choices=[('DRAFT', 'Lưu nháp'), ('PUBLISHED', 'Đăng ngay')], default='PUBLISHED', max_length=20, verbose_name='Trạng thái')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Trạng thái hiển thị')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian đăng')),
                ('display_until', models.DateTimeField(blank=True, null=True, verbose_name='Hiển thị đến')),
                ('priority', models.IntegerField(default=0, verbose_name='Độ ưu tiên')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='Thẻ meta title')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Thẻ meta description')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Tác giả')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Bài viết',
                'verbose_name_plural': 'Danh sách bài viết',
                'ordering': ['-priority', '-published_at', '-created_at'],
            },
        ),
    ]
