# Generated by Django 4.2.30 on 2026-05-12 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('order_code', models.CharField(max_length=50, unique=True, verbose_name='Mã đơn hàng')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Tổng tiền')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Chờ thanh toán'), ('PAID', 'Đã thanh toán'), ('FAILED', 'Thất bại'), ('REFUNDED', 'Đã hoàn tiền')], default='PENDING', max_length=20, verbose_name='Trạng thái thanh toán')),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Chờ bàn giao'), ('DELIVERED', 'Đã bàn giao'), ('FAILED', 'Gặp lỗi')], default='PENDING', max_length=20, verbose_name='Trạng thái bàn giao')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Danh sách đơn hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Giá lúc mua')),
                ('delivery_data', models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu bàn giao')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='account.account', verbose_name='Tài khoản')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn hàng',
                'verbose_name_plural': 'Chi tiết đơn hàng',
            },
        ),
    ]
