# Generated by Django 4.2.30 on 2026-06-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề banner')),
                ('position', models.CharField(choices=[('HOME_TOP', 'Trang chủ - Top'), ('HOME_MIDDLE', 'Trang chủ - Giữa'), ('HOME_BOTTOM', 'Trang chủ - Dưới'), ('SIDEBAR', 'Sidebar')], default='HOME_TOP', max_length=50, verbose_name='Vị trí hiển thị')),
                ('link_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Liên kết chuyển hướng')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('image_url', models.CharField(max_length=500, verbose_name='Đường dẫn ảnh')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả banner')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái hiển thị')),
                ('devices', models.JSONField(default=list, verbose_name='Thiết bị hiển thị')),
                ('show_in_home', models.BooleanField(default=True, verbose_name='Hiển thị trong trang chủ')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian bắt đầu')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian kết thúc')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'db_table': 'banner',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
