# Generated by Django 4.2.30 on 2026-05-12 10:25

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xóa')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Địa chỉ email')),
                ('avatar', models.TextField(blank=True, null=True, verbose_name='Ảnh đại diện')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Số dư')),
                ('role', models.CharField(choices=[('USER', 'Người dùng'), ('ADMIN', 'Quản trị viên'), ('SUPER_ADMIN', 'Siêu quản trị'), ('MODERATOR', 'Điều phối viên')], default='USER', max_length=30, verbose_name='Vai trò')),
                ('status', models.CharField(choices=[('ACTIVE', 'Đang hoạt động'), ('BANNED', 'Đã bị khóa'), ('PENDING', 'Chờ xác thực')], default='ACTIVE', max_length=20, verbose_name='Trạng thái')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Đã xác thực email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Danh sách người dùng',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
